django/app/urls.py
from django.urls import URLPattern, path
from django.conf.urls import url
from .views import Test, Signin , Turfs



urlpatterns = [
    path('', Test.as_view(), name="base"),
    path('login/', Signin.as_view(), name="sign-in"),
    

    path('turfs/', Turfs.as_view(), name="turfs"),
]

django/myturf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings  
from django.conf.urls.static import static  


urlpatterns = [
    path('', include('User.urls')),
    path('shop/', include('e_commerce.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home/', include('app.urls')),
    path('', include('User.urls')),
    path('',include('dashboard.urls')),
    path('',include('accounts.urls')),

]


if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

django/User/models.py
from email.policy import default
from unicodedata import category
from django.db import models
from unittest.util import _MAX_LENGTH
from datetime import datetime,timedelta
from dashboard.models import CategoriesModel
# Create your models here.


   
class MatchModel(models.Model):
    category = models.ForeignKey(CategoriesModel, on_delete=models.CASCADE)
    date= models.DateField(blank=True)
    start_time= models.DateTimeField(max_length=30,default=datetime.now(),blank=True)
    end_time= models.DateTimeField(max_length=30,default=datetime.now(),blank=True)
    locality = models.CharField(max_length=30,null=True,blank=False)
    creator = models.CharField(max_length=30,null=True,blank=False)
    status = models.CharField(default="Upcoming",max_length=30,null=False,blank=False)
    slots =models.IntegerField(default=2,null=False,blank=False)
    slot_available =models.IntegerField(default = 1,null=False,blank=False)
    cron =models.IntegerField(default = 1,null=True,blank=False)


class RequestModel(models.Model):
    match_id = models.ForeignKey(MatchModel, on_delete=models.CASCADE)
    category=models.ForeignKey(CategoriesModel, on_delete=models.CASCADE)
    username=models.CharField(max_length=30,null=False,blank=False)
    phoneno=models.CharField(max_length=16,default=7414414141)
    status=models.CharField(default="Pending",max_length=30,null=False,blank=False)
    date= models.DateField(blank=True)
    start_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    end_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    locality = models.CharField(max_length=30,null=True,blank=False)

    
class TournamentModel(models.Model):
    category = models.CharField(max_length=30,null=False,blank=False)
    start_date= models.DateField(blank=True)
    end_date= models.DateField(blank=True) 
    start_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    end_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    locality = models.CharField(max_length=30,null=True,blank=False)
    creator = models.CharField(max_length=30,null=True,blank=False)
    status = models.CharField(default="Upcoming",max_length=30,null=False,blank=False)
    teams =models.IntegerField(default=1,null=False,blank=False)
    team_space_available =models.IntegerField(default = 1,null=False,blank=False)

class TournamentRequestModel(models.Model):
    tournament_id = models.ForeignKey(MatchModel, on_delete=models.CASCADE)
    category=models.CharField(max_length=30,null=False,blank=False)
    username=models.CharField(max_length=30,null=False,blank=False)
    # phoneno=models.CharField(max_length=16,default=7414414141)
    status=models.CharField(default="Pending",max_length=30,null=False,blank=False)
    start_date= models.DateField(blank=True)
    end_date= models.DateField(blank=True) 
    start_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    end_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    locality = models.CharField(max_length=30,null=True,blank=False)

# class CreateTeamModel(models.Model):
#     Name = models.CharField(max_length=30,blank=False,null=False)





    # def __str__(self):
    #     return str(self.category)

django/User/forms.py
from pickle import NONE
from time import time
from django import forms
from django.forms import ModelForm
# from requests import request
# from django.contrib.auth import authenticate
from .models import *
from datetime import datetime
from pytz import timezone
from dashboard.models import CategoriesModel


class RequestForm(ModelForm):
    category = forms.ModelChoiceField(queryset=CategoriesModel.objects.all())
    date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control','readonly':'true','type': 'date'}))
    start_time = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control','readonly':'true','type': 'time'}))
    end_time = forms.TimeField(widget=forms.TimeInput(attrs={'class': 'form-control','readonly':'true','type': 'time'}))
    username= forms.CharField(widget=forms.HiddenInput(attrs={'class': 'form-control','readonly':'true'}))
    locality=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control','readonly':'true'}))
    status=forms.CharField(widget=forms.HiddenInput())
    # match_id= forms.ModelMultipleChoiceField(queryset=RequestModel.objects.all())
    match_id=forms.IntegerField(widget=forms.HiddenInput())
    phoneno=forms.IntegerField(widget=forms.HiddenInput())
    class Meta():
        model = RequestModel    
        # exclude = '__all__'
        fields =('category','date','start_time','end_time','username','locality','status','phoneno')
    

    def __init__(self,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(RequestForm, self).__init__(*args, **kwargs)
        self.fields['category'].disabled = True



    def clean(self):
        print("---------------Inside RequestForm's Clean Method-------------------")
        self.cleaned_data = super().clean()
        print(self.cleaned_data.get('match_id'))
        print(self.cleaned_data.get('category'))
        match=MatchModel.objects.get(id=int(self.cleaned_data.get('match_id')))
        print(match.category)
        if self.cleaned_data.get('category') != match.category:
            self._errors['category']=self.error_class(['Do not change the category'])
            print(" category  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('date')!=match.date:
            self._errors['date']=self.error_class(['Do not change the date'])
            print("date  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('start_time')!=match.start_time.astimezone(timezone('Asia/Kolkata')).time():
            self._errors['start_time']=self.error_class(['Do not change the start_time'])
            print("start_time   erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('end_time')!=match.end_time.astimezone(timezone('Asia/Kolkata')).time():
            self._errors['end_time']=self.error_class(['Do not change the end_time'])
            print("end_time  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('locality')!=match.locality:
            self._errors['locality']=self.error_class(['Do not change the locality'])
            print("locality  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")   
        if self.cleaned_data.get('username')!=self.request.user.username:
            self._errors['username']=self.error_class(['Do not change the username'])
            print("username  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")  
        # print("phone number in form",self.cleaned_data.get('phoneno'),"its type is",type(self.cleaned_data.get('phoneno')))
        # print("phone number in session",self.request.user.phone,"its type is",type(self.request.user.phone))
        if self.cleaned_data.get('phoneno')!=int(self.request.user.phone):
            self._errors['phoneno']=self.error_class(['Do not change the phone number'])
            print("phone number  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr") 
        if self.cleaned_data.get('status')!="Pending":
            self._errors['status']=self.error_class(['Do not change the status'])
            print("status  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        else:
            print("no erorrrrrrrrrrrrrrrrrrrrrrr")
        return self.cleaned_data

# choices=OPTIONS


class creatematchForm(ModelForm):

    options =[
        ("Cricket", "Cricket"),
        ("Football", "Football"),
        ("Baseball", "Baseball"),
        ("Badminton", "Badminton"),
        ("Tennis", "Tennis"),
        ("Volleyball","Volleyball"),
        ("Basketball","Basketball")
    ]
    # cat=CategoriesModel.objects.all().values_list('category')
    # print(cat)
    # print("------------------------hardcoded options--------------------------",options)
    # options1 =[
    #     # for c in cat:
    #     #     (c,c)
    # ]
    # print(options1)

    category= forms.ModelChoiceField(queryset=CategoriesModel.objects.all())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time_f = forms.TimeField(required=False,widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    end_time_f = forms.TimeField(required=False, widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    start_time = forms.DateTimeField(widget=forms.HiddenInput())
    end_time = forms.DateTimeField(widget=forms.HiddenInput())
    slots = forms.IntegerField()#nos = number of slots           
    creator= forms.CharField(widget=forms.HiddenInput())
    locality=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    # status=forms.CharField(widget=forms.HiddenInput())
    slot_available=forms.IntegerField(widget=forms.HiddenInput())
    # cron=forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = MatchModel
        fields = 'category','date','start_time_f','end_time_f','start_time','end_time','slots','creator','locality','creator'
    
    def __init__(self,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(creatematchForm, self).__init__(*args, **kwargs)

    def clean(self):
        print("hasgfsdyfgsdhjfdg")
        self.cleaned_data = super().clean()
        slots=self.cleaned_data.get('slots')
        creator=self.cleaned_data.get('creator')
        status=self.cleaned_data.get('status')
        start_time_f=self.cleaned_data.get('start_time_f')
        end_time_f=self.cleaned_data.get('end_time_f')
        print(slots)
        if slots != None and slots >= 2:
            self.cleaned_data['slot_available']=slots-1
        else :
            self._errors['slots']=self.error_class(['No of slots can not be less than 2'])
        self.cleaned_data['creator']=self.request.user.username
        if creator !=  self.request.user.username:
            self._errors['creator']=self.error_class([''])
        # if status != "Upcoming":
        #     self._errors['status']=self.error_class([''])
        self.cleaned_data['status']="Upcoming"
        if   start_time_f != None and end_time_f !=None :
                if start_time_f >= end_time_f:
                    self._errors['start_time_f']=self.error_class(['Start time can not be more than end time'])
        elif  start_time_f == None:
                self._errors['start_time_f']=self.error_class(['Start time must be time type'])
        elif  end_time_f == None:
                self._errors['end_time_f']=self.error_class(['End time must be time type'])
        print("khsfdagjfdghsuj",slots,self.cleaned_data['slot_available'])
        return self.cleaned_data



class updatematchform(ModelForm):

    options =[
        ("Cricket", "Cricket"),
        ("Football", "Football"),
        ("Baseball", "Baseball"),
        ("Badminton", "Badminton"),
        ("Tennis", "Tennis"),
        ("Volleyball","Volleyball"),
        ("Basketball","Basketball")
    ]

    match_id = forms.ModelChoiceField(queryset=MatchModel.objects.all(),widget=forms.HiddenInput())
    category= forms.ModelChoiceField(queryset=CategoriesModel.objects.all())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time_f = forms.TimeField(required=False,widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    end_time_f = forms.TimeField(required=False, widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    start_time = forms.DateTimeField(widget=forms.HiddenInput())
    end_time = forms.DateTimeField(widget=forms.HiddenInput())
    slots = forms.IntegerField()#nos = number of slots           
    creator= forms.CharField(widget=forms.HiddenInput())
    locality=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    # status=forms.CharField(widget=forms.HiddenInput())
    slot_available=forms.IntegerField(widget=forms.HiddenInput())
    # cron=forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = MatchModel
        fields = 'category','date','start_time_f','end_time_f','start_time','end_time','slots','creator','locality','creator'
    
    def __init__(self,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(updatematchform, self).__init__(*args, **kwargs)

    def clean(self):
        print("hasgfsdyfgsdhjfdg")
        self.cleaned_data = super().clean()
        slots=self.cleaned_data.get('slots')
        creator=self.cleaned_data.get('creator')
        status=self.cleaned_data.get('status')
        start_time_f=self.cleaned_data.get('start_time_f')
        end_time_f=self.cleaned_data.get('end_time_f')
        print(slots)
        if slots != None and slots >= 2:
            self.cleaned_data['slot_available']=slots-1
        else :
            self._errors['slots']=self.error_class(['No of slots can not be less than 2'])
        self.cleaned_data['creator']=self.request.user.username
        if creator !=  self.request.user.username:
            self._errors['creator']=self.error_class([''])
        # if status != "Upcoming":
        #     self._errors['status']=self.error_class([''])
        self.cleaned_data['status']="Upcoming"

django/templates/Tournaments/create-tournament.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}



<section class="ecommerce-addstock-section container-fluid my-3"  >
    <!-- ecommerce topbar -->
    {% if messages %}
    {% for message in messages %}
        <p class="d-none" id="messagetag">{{message.tags}}</p>
        <p class="d-none " id="messagecontent">{{message}}</p>
    {% endfor %}
      {% endif %}
    <div class="ecomerce-top-bar ">
        <div class="row">
                <h1 class=" mt-5"style="text-align:center">CREATE YOUR OWN TOURNAMENT</h1>
        </div>
    </div>
    <!-- ecommerce main section -->
    <div class="ecom-addstock my-3">
        <div class="bg-white col-md-6 mx-auto mt-5 p-5">
            <div class="">
                <form method="POST" id="createtournament">
                    {% csrf_token %}
                    
        
                    {% for addForm in form.visible_fields %}
                                
                       
                        {% if addForm.label != "Category" %}
                        <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                            {% render_field addForm class="form-control" placeholder="Place Holder" min="1"%}
                            {% if addForm.type != "hidden"%}
                            <label >{{addForm.label}}</label>
                            {%endif%}
                            <p>{{addForm.type}}</p>
                        </div>
                        {% else %}
                            {% render_field form.category class="form-select form-select-lg mb-4" aria-label=".form-select-lg example" name="category" id="category" %}
                        {% endif %}
                        <span class="text-danger">{{addForm.errors}}</span>
                        
        
                    {% endfor %}
                    {%for dontForm in form.hidden_fields%}
                    {% render_field dontForm %}
                    {%endfor%}
                        <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>

<script>document.getElementById('create-tournament-li').classList.add('active')</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
      
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
  <script type="text/javascript">
     $(document).ready(function(){
        let tag=$('#messagetag').html()
        let message = $('#messagecontent').html()
          if( tag == 'error'){
            toastr.error(message);
            $('#createtournament').trigger('reset');
          }
          if( tag == 'success' ){
            toastr.success(message);
            $('#createtournament').trigger('reset');
          }
      });
      $(document).ready(function() {
      var today = new Date().toISOString().split('T')[0];
      $("#id_start_date").attr('min', today);
      $("#id_end_date").attr('min', today);

      $('#createtournament').trigger('reset');
      });
  </script>


<style>
.bd-example{
      display:flex;
      flex-direction:column;
      align-items:center;
      width: 75rem;
      height: 43rem;
      
      

}
</style>



{% endblock content %}

django/templates/Tournaments/edit-tournaments.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
<section class="ecommerce-addstock-section container-fluid my-3" >
  <!-- ecommerce topbar -->
  {% if messages %}
  {% for message in messages %}
      <p class="d-none" id="messagetag">{{message.tags}}</p>
      <p class="d-none " id="messagecontent">{{message}}</p>
  {% endfor %}
    {% endif %}
  <div class="ecomerce-top-bar ">
      <div class="row">
              <h1 class=" mt-5"style="text-align:center">EDIT YOUR TOURNAMENT</h1>
      </div>
  </div>
  <!-- ecommerce main section -->
  <div class="ecom-addstock my-3">
      <div class="bg-white col-md-6 mx-auto mt-5 p-5">
          <div class="">
              <form method="POST">
                  {% csrf_token %}
                  
      
                  {% for addForm in form.visible_fields %}
                              
                     
                      {% if addForm.label != "Category" %}
                      <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                          {% render_field addForm class="form-control" placeholder="Place Holder" %}
                          {% if addForm.type != "hidden"%}
                          <label >{{addForm.label}}</label>
                          {%endif%}
                          <p>{{addForm.type}}</p>
                      </div>
                      {% else %}
                          {% render_field form.category class="form-select form-select-lg mb-4" aria-label=".form-select-lg example" name="category" id="category" %}
                      {% endif %}
                      <span class="text-danger">{{addForm.errors}}</span>
                      
      
                  {% endfor %}
                  {%for dontForm in form.hidden_fields%}
                  {% render_field dontForm %}
                  {%endfor%}
                      <button class="btn btn-primary" type="submit">Submit</button>
              </form>
          </div>
      </div>
  </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
      
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
  <script type="text/javascript">
     $(document).ready(function(){
        let tag=$('#messagetag').html()
        let message = $('#messagecontent').html()
          if( tag == 'error'){
            toastr.error(message);
          }
          if( tag == 'success' ){
            toastr.success(message);
          }
      });
      $(document).ready(function() {
      var today = new Date().toISOString().split('T')[0];
      $("#id_date").attr('min', today);
      });

  </script>
{%endblock content%}

django/templates/Tournaments/my-tournament.html
{% extends 'layouts/base.html' %}
{% block content %}
<div class="container-fluid">
    {% if tournaments%}
    <div class="row bg-light justify-content-around">
        {% if tournaments %}
        <!-- <h1>feagrthdth</h1> -->
<div class="row bg-light justify-content-around container-fluid">
        {% for r in tournaments %}
    <div class="column col-md-4">
        <div class="card p-2 m-4">
            {% if r.category == "Cricket" %}
            <img src="https://cdn.britannica.com/47/148847-050-C4FB5341/Cricket-bat-ball.jpg" class="card-img-top flex" alt="Product 1" style="height:350px;">
            {% elif r.category == "Football" %}
            <img src="https://images.squarespace-cdn.com/content/v1/51e6a2b7e4b038b7a667f1b3/1375240864715-15RNHVOTAV215YF2R60V/PES%2B2014%2BBall%2Bgrass.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Baseball" %}
            <img src="https://techcrunch.com/wp-content/uploads/2019/03/GettyImages-844016022.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Badminton" %}
            <img src="https://gumlet.assettype.com/dtnext/import/Articles/2022/Feb/202202200142305523_Ball-Badminton-Nationals-in-Dindigul-from-Feb-22_SECVPF.gif?w=1200&h=675&auto=format%2Ccompress&fit=max" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Tennis" %}
            <img src="https://thumbs.dreamstime.com/b/tennis-ball-racket-16093106.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Volleyball" %}
            <img src="https://sportslounge.co.in/file/2020/09/volleyball.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Basketball" %}
            <img src="https://btcpeers.com/content/images/2022/04/Basketball-Swish.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            
            {%endif%}
            <div class="card-body p-1 ">
            <h2 class="card-text p-1">{{r.category}}</h2>
            <p class="card-text ">start-date:{{r.start_date|date:"Y-m-d"}}</p>
            <p class="card-text ">end-date:{{r.end_date|date:"Y-m-d"}}</p>
            <p class="card-text">Start-Time:{{r.start_time|time:"H:i:s"}}</p>
            <p class="card-text">End-Time:{{r.end_time|time:"H:i:s"}}</p>
            <p class="card-text">Available Slots:{{r.team_space_available}}/{{r.team_space_available}}</p>
            <p class="card-text">Locality:{{r.locality}}</p>
            {% if r.creator == request.user.username %}
            <a href="edit/{{r.id}} "  class="btn btn-primary">
                EDIT
            </a>
            {%else%}
            <p class="card-text ">Organized By:{r.creator}}</p>
            {%endif%}
            </div>
        </div>
    </div>
    {%endfor%}
    </div>
 {% else %}

 <p>effffffffffffffffffffffffffffffffffffffffffffff</p>
 <div class="row bg-light justify-content-center">
    <div class="column col-md-4 justify-content-md-around">
        <div class="card text-white bg-soft-info m-5" > 
          <div class="card-body">   
            <h3 class="mt-3 text-center">There aren't any matches you have created or joined</h3>
            <p class="mt-3 text-center">
              Interested in creating your own tournament<a class="nav-link " href="{% url 'create-tournament' %}" id="create-tournament-li">Click here</a>
            </p>
          </div>
          </div>
    </div>
    </div>
    {%endif%}
</div>

{%endif%}
<script>
    document.getElementById('my-tournaments-li').classList.add('active')
  
</script>




{% endblock content %}

django/templates/Tournaments/requested-tournaments.html
{% extends 'layouts/base.html' %}
{% block content %}


<div class="container-fluid">
  {%if tournaments%}
<div class="container-fluid">
  <div class="row  bg-soft-light">
    {% for r in tournaments%}
      <div class="column col-md-4">
          <div class="card p-2 m-5">
            {% if r.category == "Cricket" %}
            <img src="https://cdn.britannica.com/47/148847-050-C4FB5341/Cricket-bat-ball.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Football" %}
            <img src="https://images.squarespace-cdn.com/content/v1/51e6a2b7e4b038b7a667f1b3/1375240864715-15RNHVOTAV215YF2R60V/PES%2B2014%2BBall%2Bgrass.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Baseball" %}
            <img src="https://techcrunch.com/wp-content/uploads/2019/03/GettyImages-844016022.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Badminton" %}
            <img src="https://gumlet.assettype.com/dtnext/import/Articles/2022/Feb/202202200142305523_Ball-Badminton-Nationals-in-Dindigul-from-Feb-22_SECVPF.gif?w=1200&h=675&auto=format%2Ccompress&fit=max" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Tennis" %}
            <img src="https://thumbs.dreamstime.com/b/tennis-ball-racket-16093106.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Volleyball" %}
            <img src="https://sportslounge.co.in/file/2020/09/volleyball.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            {% elif r.category == "Basketball" %}
            <img src="https://btcpeers.com/content/images/2022/04/Basketball-Swish.jpg" class="card-img-top" alt="Product 1" style="height:350px;">
            
            {%endif%}
              <div class="card-body">
            <h2>{{r.category}}</h2>
                <p class="card-text text-dark">Date of r:{{r.date|date:"Y-m-d"}}</p>
                <p class="card-text text-dark">Time:{{r.start_time|time:"H:i:s"}}</p>
                <p class="card-text text-dark">Time:{{r.end_time|time:"H:i:s"}}</p>
                <p class="card-text text-dark">Available Slots:{{r.slot_available}}/{{r.slots}}</p>
                <p class="card-text text-dark">Locality:{{r.locality}}</p>
                <a  class="btn btn-primary" href="cancel/{{r.id}}">
                  Cancel
                </a>
              </div>
            </div>
        </div>
     {%endfor%}
  </div>
</div>
 {%else%}
 <div class="row bg-light justify-content-center">
  <div class="column col-md-4 justify-content-md-around">
      <div class="card text-white bg-soft-info m-5" > 
        <div class="card-body">   
          <h3 class="mt-3 text-center">There aren't any tournaments you have requested to join</h3>
          <p class="mt-3 text-center">
            Interested in creating your own tournaments<a class="nav-link " href="{% url 'create-tournament' %}" id="create-tournament-li">Click here</a>
          </p>
        </div>
        </div>
  </div>
  </div>
  {%endif%}
</div>
<script>
    document.getElementById('requested-tournament-li').classList.add('active')
</script>
{% endblock content %}